# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  code_climate:
    repo_token: 8432fd00f5d96695457d25cf9216a92f8629b8997a68bcdccc093852ec717ee5

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install --dev
  - phpenv rehash

script: 
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi'

after_success: vendor/bin/test-reporter
